### ISSUE TITLE
Facing problem with QB connect. not able to connect whenever credential is correct 

### ISSUE THREAD

**Issue by manojintorque** [QuickBlox/quickblox-javascript-sdk#312]
[**Environment](url) details**
*(Operating system, browser information, SDK version)*
Windows 10,chrom

**Did this work before?**
No

**code**

QB.chat.connect({userId: user['id'], password: $scope.U_Email+$scope.U_Mobile}, function(err, roster) {
						  if (err) {
							  console.log(err);
							  console.log('Not Connect');
						  } else {
							  //console.log(roster);
							  console.log('Connected');
							  QB.chat.onMessageListener = onMessage;
						  }
					});

**Actual behavior**
{code: 422, status: "error", detail: "Status.CONNFAIL - The connection attempt failed", message: "Unprocessable Entity"}code: 422detail: "Status.CONNFAIL - The connection attempt failed"message: "Unprocessable Entity"status: "error"__proto__: Object
qbChatController.js:222 Not Connect
![error](https://user-images.githubusercontent.com/35804782/36656299-ba69a7b0-1aed-11e8-9fd3-7117570d3659.PNG)

**Comment by dimaspirit** [comment]
@manojintorque Hi, last week there were some issues and now they are solved. 
Can you confirm the error now?

**Comment by manojintorque** [comment]
@dimaspirit  Yeah i will check it but it work sometime or sometime not so  i'm confused what happen actually problem in my code or some other issue so put code and error to got proper guideline and thank you for quick response ! :)

**Comment by manojintorque** [comment]
@dimaspirit  but error still same not solved :( so i have to change quickblox.min.js file? 
if yes than share link here

**Comment by dimaspirit** [comment]
Could you share your config to check out this issue?
If you are Enterprise client better use [HelpDesk](https://quickblox.com/contact/).

To make sure that SDK working uses our [specs](https://quickblox.github.io/quickblox-javascript-sdk/spec/SpecRunner.html). 
If you want to check your server change[ CREDS and CONFIG, add 2 users](https://github.com/QuickBlox/quickblox-javascript-sdk/blob/gh-pages/spec/config.js#L43) in config.

**Comment by manojintorque** [comment]
Hello @dimaspirit  this is code which is implemented 
var QBApp = {
  appId: 66237,
  authKey: 'jpzw3EL3e5yN-vz',
  authSecret: '68hYEeS7JEBqKDs'
};

$scope.QBInit = function(){
		// Init QuickBlox application here
		QB.init(QBApp.appId, QBApp.authKey, QBApp.authSecret);

		QB.createSession(function(err,result){
			//console.log('Session create callback', err);
			$rootScope.qbToken = result['token'];
			localStorage.setItem('qbtoken', result['token']);
		});
	}



var loginparams = { 'login': $scope.U_Mobile, 'password': $scope.U_Email+$scope.U_Mobile,'token':$rootScope.qbToken };
		 QB.login(loginparams, function(err, user){
				if (user) {
					console.log(user['id']);
					console.log($scope.U_Email+$scope.U_Mobile);
					
					QB.chat.connect({userId: user['id'], password: $scope.U_Email+$scope.U_Mobile}, function(err, roster) {
						  if (err) {
							  console.log(err);
							  console.log('Not Connect');
						  } else {
							  //console.log(roster);
							  console.log('Connected');
							  QB.chat.onMessageListener = onMessage;
						  }
					});
					
				}else{
					//console.log(err);
				}
		 });
		 
		 
		 
		 function onMessage(id, msg) {
			 // add message to ui
		 }

**Comment by dimaspirit** [comment]
Could you set in [config ](https://quickblox.com/developers/Javascript#Configuration) ? 
 ```
chatProtocol: {
    active: 1 
}
```

**Comment by manojintorque** [comment]
@dimaspirit  Yes i was set congif but after add config variable this request  "https://chat.quickblox.com:5281/" fire in background  again and again . and not able to get instant messages !!

**Comment by dimaspirit** [comment]
Ok, could you use our specs (uses your config) to check out that is it issues with SDK or your code?

**Comment by dimaspirit** [comment]
Give us logs, please

**Comment by manojintorque** [comment]
@dimaspirit 
var QBApp = {
  appId: **id**,
  authKey: *authKey*,
  authSecret: **secret**
};
var CONFIG = {
  chatProtocol: {
    active: 1
  }
};

QB.init(QBApp.appId, QBApp.authKey, QBApp.authSecret,CONFIG);


After use CONFIG variable this happen in background ,so not able to get messages instant 
![123456](https://user-images.githubusercontent.com/35804782/36844841-4ea945e6-1d7a-11e8-99da-02ccb6d3e663.png)

**Comment by williamtran1988** [comment]
I have a same the problem, is it resolved now?

I could login on my windows computer, but on our customer side could not and got exactly the same issue like this. I have tried to use customer's account to login it is working well from my side.
In my opinion, we have a problem with localization in request data or timestamp?

**Comment by vadimkhmyrovqb** [comment]
@manojintorque @williamtran1988 Is this issue still relevant?

**Comment by ghost** [comment]
Hello QuickBlox customer,

This is Nikolay from QuickBlox support.

The issue was closed as it was outdated.

Please check the relevant section of our documentation here:
[https://docs.quickblox.com/docs/js-authentication](https://docs.quickblox.com/docs/js-authentication)

Also, please update the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Additionally, please check our new sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

If it is still relevant after reviewing the updated information, feel free to open a new issue.

Have a nice day.
